export {default as Javascript} from './images/javascript.png';
export {default as HTML} from './images/html.png';
export {default as CSS} from './images/css.png';
export {default as Arrow} from './images/arrow.png';
export {default as ChakraUI} from './images/chakraui.png';
export {default as Figma} from './images/figma.png';
export {default as FramerMotion} from './images/framermotion.png';
export {default as Git } from './images/git.png';
export {default as Github } from './images/github.png';
export {default as Next } from './images/next.png';
export {default as Next2 } from './images/next_2.png';
export {default as Photoshop } from './images/photoshop.png';
export {default as Python } from './images/python.png';
export {default as React1 } from './images/react.png';
export {default as Redux1 } from './images/redux.png';
export {default as SASS } from './images/sass.png';
export {default as Tailwind } from './images/tailwind.png';
export {default as Theodinproject} from './images/theodinproject.png';
export {default as Typescript } from './images/typescript.png'; 
export {default as VSCode } from './images/vscode.png';
export {default as Firebase } from './images/firebase.png';
export {default as NodeJS } from './images/nodejs.png';
